# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bazel

on:
  push:
    branches:
      - master
      - main

  pull_request:
    types: [opened, synchronize]

  merge_group:
    types:
      - checks_requested

  # Allow manual invocation, for testing.
  workflow_dispatch:

# Declare default workflow permissions to be read-only.
permissions: read-all

# Cancel any previously-started but still active runs on the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  test:
    name: Test with Bazel
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Hardware optimizers.
        hardware_opt: [avx,sse,basic]
        # Optimizers for parallelism.
        parallel_opt: [openmp,nopenmp]

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelisk-version: 1.x
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run C++ tests
        run: |
          bazel test --config=${{ matrix.hardware_opt }} \
          --config=${{ matrix.parallel_opt }} tests:all
      - name: Run sample simulation
        run: |
          bazel run --config=${{ matrix.hardware_opt }} \
          --config=${{ matrix.parallel_opt }} apps:qsim_base \
          -- -c circuits/circuit_q24

  test-san:
    name: Sanitizer tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Test sanitizers
        sanitizer_opt: [msan,asan]

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelisk-version: 1.x
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Upgrade libc
      # An LLVM update broke this test, fix per is https://bugs.llvm.org/show_bug.cgi?id=27310.
        run: |
          sudo apt update
          sudo apt-get upgrade libc-bin
      - name: Run C++ tests
        run: |
          bazel test --config=avx --config=openmp \
          --config=${{ matrix.sanitizer_opt }} tests:all

  test-mem:
    name: Test with tcmalloc
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelisk-version: 1.x
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Install google-perftools for tcmalloc
        run: sudo apt-get install libgoogle-perftools-dev
      - name: Run C++ tests
        run: |
          bazel test --config=avx --config=openmp \
          --config=tcmalloc tests:all
