# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI test – Bazel tests
run-name: Run optimizer and sanitizer tests using Bazel

on:
  push:
    branches:
      - master
      - main

  pull_request:
    types: [opened, synchronize]

  merge_group:
    types:
      - checks_requested

  workflow_dispatch:

permissions: read-all

concurrency:
  # Cancel any previously-started but still active runs on the same branch.
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  test-bazel:
    name: Test with Bazel
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        # Hardware optimizers.
        hardware_opt: [avx, sse, basic]
        # Optimizers for parallelism.
        parallel_opt: [openmp, nopenmp]

    steps:
      - name: Check out a copy of the git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: ${{github.workflow}}
          bazelisk-cache: true
          external-cache: true
          repository-cache: true
          bazelrc: |
            common --announce_rc
            common --verbose_failures
            common --auto_output_filter=none
            common --remote_upload_local_results=false
            common --jobs 2

      - name: Set up Python with caching of pip dependencies
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.11'
          architecture: x64
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Check out git submodules
        run: git submodule update --init --recursive

      - name: Install qsim requirements
        run: python3 -m pip install -r requirements.txt

      - name: Run C++ tests
        run: |
          bazel test --config=${{ matrix.hardware_opt }} \
          --config=${{ matrix.parallel_opt }} tests:all

      - name: Run sample simulation
        run: |
          bazel run --config=${{ matrix.hardware_opt }} \
          --config=${{ matrix.parallel_opt }} apps:qsim_base \
          -- -c circuits/circuit_q24

  test-san:
    name: Sanitizer tests
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    strategy:
      matrix:
        # Memory and address sanitizers.
        sanitizer_opt: [msan, asan]
    steps:
      - name: Check out a copy of the git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: ${{github.workflow}}
          bazelisk-cache: true
          external-cache: true
          repository-cache: true
          bazelrc: |
            common --announce_rc
            common --verbose_failures
            common --auto_output_filter=none
            common --remote_upload_local_results=false
            common --jobs 2

      - name: Set up Python with caching of pip dependencies
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.11'
          architecture: x64
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Check out git submodules
        run: git submodule update --init --recursive

      - name: Install qsim requirements
        run: |
          python3 -m pip install -r requirements.txt

      # - name: Upgrade libc
      # # An LLVM update broke this test, fix per is https://bugs.llvm.org/show_bug.cgi?id=27310.
      #   run: |
      #     sudo apt update
      #     sudo apt-get upgrade libc-bin

      - name: Run C++ tests
        run: |
          bazel test --config=avx --config=openmp \
          --config=${{ matrix.sanitizer_opt }} tests:all

  test-mem:
    name: Test with tcmalloc
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Check out a copy of the git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: ${{github.workflow}}
          bazelisk-cache: true
          external-cache: true
          repository-cache: true
          bazelrc: |
            common --announce_rc
            common --verbose_failures
            common --auto_output_filter=none
            common --remote_upload_local_results=false
            common --jobs 2

      - name: Set up Python with caching of pip dependencies
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.11'
          architecture: x64
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Check out git submodules
        run: git submodule update --init --recursive

      - name: Install qsim requirements
        run: |
          python3 -m pip install -r requirements.txt

      - name: Install google-perftools for tcmalloc
        run: sudo apt-get install libgoogle-perftools-dev

      - name: Run C++ tests
        run: |
          bazel test --config=avx --config=openmp \
          --config=tcmalloc tests:all
