name: Build all wheels for testing

on:
  push:
    # Build wheels when pushing to master.
    branches:
      - master

  # Build wheels for any PRs.
  pull_request:

  # Allow manual invocation, for testing.
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            name: mac_x64
            env:
              macosx_deployment_target: "13.0"
            cibw:
              build: "cp310* cp311* cp312*"
          - os: ubuntu-24.04
            name: manylinux_2_28
            cibw:
              arch: x86_64
              build: "cp39* cp310* cp311* cp312*"
              manylinux_image: manylinux_2_28
          - os: windows-2019
            name: win_amd64
            architecture: x64
            cibw:
              build: "cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64"
    env:
      MACOSX_DEPLOYMENT_TARGET: "${{ matrix.env.macosx_deployment_target }}"
      CIBW_BUILD: "${{ matrix.cibw.build || '*' }}"
      CIBW_SKIP: "*musllinux*"
      CIBW_ARCHS: "${{ matrix.cibw.arch || 'auto' }}"
      CIBW_MANYLINUX_X86_64_IMAGE: "${{ matrix.cibw.manylinux_image }}"
      CIBW_BEFORE_BUILD_MACOS: "brew install libomp llvm@19 && brew link --force libomp && export LDFLAGS='/usr/local/opt/llvm@19/lib' && export CPPFLAGS='/usr/local/opt/llvm@19/include'"
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps {wheel} && delocate-wheel --verbose --require-archs {delocate_archs} -w {dest_dir} {wheel}"
      # to install latest delocate package
      CIBW_DEPENDENCY_VERSIONS: "latest"
      # due to package and module name conflict have to temporarily move it away to run tests
      CIBW_BEFORE_TEST: "mv {package}/qsimcirq /tmp && pwd && ls -l {package}"
      CIBW_TEST_EXTRAS: "dev"
      CIBW_TEST_COMMAND: "pytest {package}/qsimcirq_tests/qsimcirq_test.py && mv /tmp/qsimcirq {package}"
    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel and twine
        # virtualenv 20.31.0 breaks cibuildwheel.
        # TODO: remove after https://github.com/pypa/cibuildwheel/issues/2380 is resolved
        run: python -m pip install cibuildwheel==2.23.3 'virtualenv<20.31'

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
          python -m pip install cmake

      # - name: Run C++ tests
      #   run: bash build_tools/test_libs.sh

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.name }}
          path: ./wheelhouse/*.whl
