# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build & test Python wheels
run-name: Build all Python wheels and test them

on:
  push:
    branches:
      - master
      - main

  # Build wheels for any PRs.
  pull_request:

  # Allow manual invocation, for testing.
  workflow_dispatch:

# Cancel any previously-started but still active runs on the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

# Declare default workflow permissions to be read-only.
permissions: read-all

jobs:
  build_wheels:
    name: >-
      Build ${{matrix.variant.os}}/${{matrix.variant.python.arch}}/py${{matrix.variant.python.version}}
    runs-on: ${{matrix.variant.os}}
    strategy:
      fail-fast: false
      matrix:
        # See the following page for a list of valid cibuildwheel arch values:
        # https://cibuildwheel.pypa.io/en/stable/options/#archs
        variant: [
          # {os: macos-13, python: '3.9',  build: cp39-macosx, arch: x86_64, target: '13.0'},
          # {os: macos-13, python: '3.10', build: cp310-macosx, arch: x86_64, target: '13.0'},
          # {os: macos-13, python: '3.11', build: cp311-macosx, arch: x86_64, target: '13.0'},
          # {os: macos-13, python: '3.12', build: cp312-macosx, arch: x86_64, target: '13.0'},
          # {os: macos-13, python: '3.13', build: cp313-macosx, arch: x86_64, target: '13.0'},

          # {os: macos-14, python: '3.9',  build: cp39-macosx, arch: arm64, target: '14.0'},
          # {os: macos-14, python: '3.10', build: cp310-macosx, arch: arm64, target: '14.0'},
          # {os: macos-14, python: '3.11', build: cp311-macosx, arch: arm64, target: '14.0'},
          # {os: macos-14, python: '3.12', build: cp312-macosx, arch: arm64, target: '14.0'},
          # {os: macos-14, python: '3.13', build: cp313-macosx, arch: arm64, target: '14.0'},

          # {os: macos-14, python: '3.9',  build: cp39-macosx, arch: x86_64, target: '14.0'},
          # {os: macos-14, python: '3.10', build: cp310-macosx, arch: x86_64, target: '14.0'},
          {os: macos-14, target: '14.0',
            python: {version: '3.11', arch: x64},
            cibw: {wheel: cp312-macosx, arch: x86_64},
          },

          # {os: macos-14, python: '3.12', build: cp312-macosx, arch: x86_64, target: '14.0'},
          # {os: macos-14, python: '3.13', build: cp313-macosx, arch: x86_64, target: '14.0'},

          # {os: macos-15, python: {version: '3.9', arch: 'x64'}, build: {cp39-macosx, arch: arm64, target: '15.0'},
          # {os: macos-15, python: '3.10', build: cp310-macosx, arch: arm64, target: '15.0'},
          # {os: macos-15, python: '3.11', build: cp311-macosx, arch: arm64, target: '15.0'},
          # {os: macos-15, python: '3.12', build: cp312-macosx, arch: arm64, target: '15.0'},
          # {os: macos-15, python: '3.13', build: cp313-macosx, arch: arm64, target: '15.0'},

          # {os: ubuntu-24.04, python: '3.9',  build: cp39-manylinux, arch: x86_64},
          # {os: ubuntu-24.04, python: '3.10', build: cp310-manylinux, arch: x86_64},
          # {os: ubuntu-24.04, python: '3.11', build: cp311-manylinux, arch: x86_64},
          # {os: ubuntu-24.04, python: '3.12', build: cp312-manylinux, arch: x86_64},
          # {os: ubuntu-24.04, python: '3.13', build: cp313-manylinux, arch: x86_64},

          # {os: windows-2019, python: '3.9',  build: cp39-win, arch: AMD64},
          # {os: windows-2019, python: '3.10', build: cp310-win, arch: AMD64},
          # {os: windows-2019, python: '3.11', build: cp311-win, arch: AMD64},
          # {os: windows-2019, python: '3.12', build: cp312-win, arch: AMD64},

          # 2025-05-13 currently these fail on GitHub.
          # {os: windows-2019, python: '3.13', build: cp313-win, arch: AMD64},
          # {os: windows-2022, python: '3.13', build: cp313-win, arch: AMD64},
        ]

          # - os: windows-2019
          #   name: win_amd64
          #   architecture: x64
          #   cibw:
          #     build: "cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64 cp313-win_amd64"
    env:
      # Note: more cibuildwheel settings are in pyproject.toml
      CIBW_BUILD: ${{matrix.variant.cibw.wheel}}_${{matrix.variant.cibw.arch}}
      CIBW_ARCHS: ${{matrix.variant.cibw.arch}}
      CIBW_ENVIRONMENT: 'MACOSX_DEPLOYMENT_TARGET=${{matrix.variant.target}}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.variant.python.version}}
          architecture: ${{matrix.variant.python.arch}}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Python tools and requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.23.3 virtualenv==20.31.2 cmake
          python -m pip install -r requirements.txt

      - run: |
          bazel build apps:all

      # - name: Run C++ tests
      #   run: bash build_tools/test_libs.sh

      # - name: Build and test wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: python-wheels-${{matrix.variant.build}}_${{matrix.variant.arch}}
      #     path: ./wheelhouse/*.whl
