# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build & test Python wheels
run-name: Build all Python wheels and test them

on:
  push:
    branches:
      - master
      - main

  # Build wheels for any PRs.
  pull_request:

  # Allow manual invocation, for testing.
  workflow_dispatch:

# Cancel any previously-started but still active runs on the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

# Declare default workflow permissions to be read-only.
permissions: read-all

jobs:
  build_wheels:
    name: >-
      Build wheel ${{matrix.conf.os}}/${{matrix.conf.py.arch}}/py${{matrix.conf.py.version}}
    runs-on: ${{matrix.conf.os}}
    strategy:
      fail-fast: false
      matrix:
        # See the following page for a list of valid cibuildwheel arch values:
        # https://cibuildwheel.pypa.io/en/stable/options/#archs
        conf: [
          # {os: macos-13, dep: '13.0', py: {version: '3.10', arch: x64}, cibw: {wheel: cp310-macosx, arch: x86_64}},
          # {os: macos-13, dep: '13.0', py: {version: '3.11', arch: x64}, cibw: {wheel: cp311-macosx, arch: x86_64}},
          # {os: macos-13, dep: '13.0', py: {version: '3.12', arch: x64}, cibw: {wheel: cp312-macosx, arch: x86_64}},
          # {os: macos-13, dep: '13.0', py: {version: '3.13', arch: x64}, cibw: {wheel: cp313-macosx, arch: x86_64}},

          # # This version fails due to https://github.com/actions/setup-python/issues/948
          # # {os: macos-14, dep: '14.0', py: {version: '3.10', arch: x64}, cibw: {wheel: cp310-macosx, arch: x86_64}},
          # {os: macos-14, dep: '14.0', py: {version: '3.11', arch: x64}, cibw: {wheel: cp312-macosx, arch: x86_64}},
          # {os: macos-14, dep: '14.0', py: {version: '3.12', arch: x64}, cibw: {wheel: cp312-macosx, arch: x86_64}},
          # {os: macos-14, dep: '14.0', py: {version: '3.13', arch: x64}, cibw: {wheel: cp313-macosx, arch: x86_64}},

          # {os: macos-14, dep: '14.0', py: {version: '3.10', arch: arm64}, cibw: {wheel: cp310-macosx, arch: arm64}},
          # {os: macos-14, dep: '14.0', py: {version: '3.11', arch: arm64}, cibw: {wheel: cp311-macosx, arch: arm64}},
          # {os: macos-14, dep: '14.0', py: {version: '3.12', arch: arm64}, cibw: {wheel: cp312-macosx, arch: arm64}},
          # {os: macos-14, dep: '14.0', py: {version: '3.13', arch: arm64}, cibw: {wheel: cp313-macosx, arch: arm64}},

          # {os: macos-15, dep: '15.0', py: {version: '3.10', arch: arm64}, cibw: {wheel: cp310-macosx, arch: arm64}},
          # {os: macos-15, dep: '15.0', py: {version: '3.11', arch: arm64}, cibw: {wheel: cp311-macosx, arch: arm64}},
          # {os: macos-15, dep: '15.0', py: {version: '3.12', arch: arm64}, cibw: {wheel: cp312-macosx, arch: arm64}},
          # {os: macos-15, dep: '15.0', py: {version: '3.13', arch: arm64}, cibw: {wheel: cp313-macosx, arch: arm64}},

          # {os: ubuntu-24.04, dep: '', py: {version: '3.10', arch: x64}, cibw: {wheel: cp310-manylinux, arch: x86_64}},
          # {os: ubuntu-24.04, dep: '', py: {version: '3.11', arch: x64}, cibw: {wheel: cp311-manylinux, arch: x86_64}},
          # {os: ubuntu-24.04, dep: '', py: {version: '3.12', arch: x64}, cibw: {wheel: cp312-manylinux, arch: x86_64}},
          # {os: ubuntu-24.04, dep: '', py: {version: '3.13', arch: x64}, cibw: {wheel: cp313-manylinux, arch: x86_64}},

          {os: windows-2019, dep: '', py: {version: '3.10', arch: x64}, cibw: {wheel: cp310-win, arch: AMD64}},
          # {os: windows-2019, dep: '', py: {version: '3.11', arch: x64}, cibw: {wheel: cp311-win, arch: AMD64}},
          # {os: windows-2019, dep: '', py: {version: '3.12', arch: x64}, cibw: {wheel: cp312-win, arch: AMD64}},
          # {os: windows-2019, dep: '', py: {version: '3.13', arch: x64}, cibw: {wheel: cp313-win, arch: AMD64}},

          # 2025-05-13 currently these fail on GitHub.
          # {os: windows-2019, py: '3.13', build: cp313-win, arch: AMD64},
          # {os: windows-2022, py: '3.13', build: cp313-win, arch: AMD64},
        ]
    env:
      # Note: additional cibuildwheel settings are in pyproject.toml
      CIBW_BUILD: ${{matrix.conf.cibw.wheel}}_${{matrix.conf.cibw.arch}}
      CIBW_ARCHS: ${{matrix.conf.cibw.arch}}
      CIBW_ENVIRONMENT: 'MACOSX_DEPLOYMENT_TARGET=${{matrix.conf.dep}}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.conf.py.version}}
          architecture: ${{matrix.conf.py.arch}}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Python tools and requirements
        run: |
          python -m pip install cibuildwheel==2.23.3 virtualenv==20.31.2 cmake
          python -m pip install -r requirements.txt

      - if: matrix.conf.os == 'windows-2019'
        shell: cmd
        run: |
          bazel build --announce_rc --show_loading_progress --verbose_failures --auto_output_filter=none --config=sse "apps:all"

      # - if: matrix.conf.os == 'windows-2019'
      #   # shell: '"C:\Program Files\Git\bin\bash.exe" -c {0}'
      #   shell: C:\Program Files\Git\bin\bash.exe
      #   run: |
      #     set -x
      #     pwd
      #     ls
      #     # bazel build --announce_rc --show_loading_progress --verbose_failures --auto_output_filter=none --config=sse "apps:all"

      - if: matrix.conf.os != 'windows-2019'
        run: |
          bazel build --announce_rc --show_loading_progress --verbose_failures --auto_output_filter=none --config=sse apps:all


      # - name: Run C++ tests
      #   run: bash build_tools/test_libs.sh

      # - name: Build and test wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: python-wheels-${{matrix.conf.build}}_${{matrix.conf.arch}}
      #     path: ./wheelhouse/*.whl
