# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CI: build & test Python wheels'
run-name: Build Python wheels and test them

on:
  push:
    branches:
      - master
      - main

  pull_request:
    types: [opened, synchronize]

  merge_group:
    types:
      - checks_requested

  workflow_dispatch:
    inputs:
      trace:
        description: 'Turn on shell script debugging'
        type: boolean
        default: true

permissions: read-all

concurrency:
  # Cancel any previously-started but still active runs on the same branch.
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  # For efficiency, we skip this workflow if the file changes only involve docs.
  # Here's an explanation of the approach used. GitHub Actions workflows can
  # have path filters (i.e., the use of "paths:" keywords on event triggers),
  # and that *would* be the natural way to run workflows only when the relevant
  # files change – except that the way GitHub branch protection rules work is:
  # "If a workflow is skipped due to path filtering [...] the checks associated
  # with that workflow will remain in a Pending state. A PR that requires those
  # checks to be successful will be blocked from merging." Our approach forgoes
  # path filters, and instead checks file changes using a preliminary job.
  decide:
    name: (Decide if wheel tests are needed)
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      proceed: >-
        github.event_name == 'workflow_dispatch' || steps.changes.outputs.notdocs
    steps:
      - if: github.event_name != 'workflow_dispatch'
        name: Check out a copy of the git repository
        uses: actions/checkout@v4

      - if: github.event_name != 'workflow_dispatch'
        name: Determine files changed by this ${{github.event_name}} event
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{github.ref_name}}
          predicate-quantifier: 'every'
          filters: |
            notdocs:
              - '!**/*.md'
              - '!docs/**'
              - '!CITATION.cff'

  build_wheels:
    if: needs.decide.outputs.proceed
    name: >-
      Build wheel
      ${{matrix.conf.os}}/${{matrix.conf.pyarch}}/py3${{matrix.conf.py}}
    needs: decide
    runs-on: ${{matrix.conf.os}}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # See the following page for a list of valid cibuildwheel arch values:
        # https://cibuildwheel.pypa.io/en/stable/options/#archs
        conf: [
          {os: ubuntu-24.04, wh: manylinux, arch: x86_64, pyarch: x64, py: 10},
          {os: ubuntu-24.04, wh: manylinux, arch: x86_64, pyarch: x64, py: 11},
          {os: ubuntu-24.04, wh: manylinux, arch: x86_64, pyarch: x64, py: 12},
          {os: ubuntu-24.04, wh: manylinux, arch: x86_64, pyarch: x64, py: 13},

          {os: macos-13, wh: macosx, arch: x86_64, pyarch: x64, py: 10},
          {os: macos-13, wh: macosx, arch: x86_64, pyarch: x64, py: 11},
          {os: macos-13, wh: macosx, arch: x86_64, pyarch: x64, py: 12},
          {os: macos-13, wh: macosx, arch: x86_64, pyarch: x64, py: 13},

          {os: macos-14, wh: macosx, arch: arm64, pyarch: arm64, py: 10},
          {os: macos-14, wh: macosx, arch: arm64, pyarch: arm64, py: 11},
          {os: macos-14, wh: macosx, arch: arm64, pyarch: arm64, py: 12},
          {os: macos-14, wh: macosx, arch: arm64, pyarch: arm64, py: 13},

          {os: macos-15, wh: macosx, arch: arm64, pyarch: arm64, py: 10},
          {os: macos-15, wh: macosx, arch: arm64, pyarch: arm64, py: 11},
          {os: macos-15, wh: macosx, arch: arm64, pyarch: arm64, py: 12},
          {os: macos-15, wh: macosx, arch: arm64, pyarch: arm64, py: 13},

          {os: windows-2019, wh: win, arch: AMD64, pyarch: x64, py: 10},
          {os: windows-2019, wh: win, arch: AMD64, pyarch: x64, py: 11},
          {os: windows-2019, wh: win, arch: AMD64, pyarch: x64, py: 12},
          # This fails with NumPy 1.x. TODO: uncomment when qsim supports np 2.
          # {os: windows-2019, wh: win, arch: AMD64, pyarch: x64, py: 13},
        ]
    steps:
      - name: Check out a copy of the git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python with caching of pip dependencies
        uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.${{matrix.conf.py}}'
          architecture: ${{matrix.conf.pyarch}}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Set up Bazel with caching
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          disk-cache: ${{github.workflow}}
          bazelisk-cache: true
          external-cache: true
          repository-cache: true

      - name: Install qsim dependencies
        run: pip install -r requirements.txt

      - if: matrix.conf.os != 'windows-2019'
        name: Run the build and test script (Windows case)
        env:
          # SHELLOPTS is used by Bash. Add xtrace when doing manual debug runs.
          SHELLOPTS: ${{inputs.trace && 'xtrace' || '' }}
        run: dev_tools/test_libs.sh --config=verbose

      - if: matrix.conf.os == 'windows-2019'
        name: Run the build and test script (non-Windows)
        env:
          pyroot: 'C:\\hostedtoolcache\\windows\\Python'
          pyexe: '${{steps.setup.outputs.python-version}}\\${{matrix.conf.pyarch}}\\python3.exe'
          SHELLOPTS: ${{inputs.trace && 'xtrace' || '' }}
        shell: cmd
        run: >-
          bash dev_tools/test_libs.sh --config=verbose
          --action_env PYTHON_BIN_PATH=${{env.pyroot}}\\${{env.pyexe}}

      - if: startsWith(matrix.conf.os, 'macos')
        name: Set cibuildwheel MACOSX_DEPLOYMENT_TARGET value on MacOS
        run: |
          set -x
          os=${{matrix.conf.os}}
          echo MACOSX_DEPLOYMENT_TARGET=${os: -2} >> "$GITHUB_ENV"

      - name: Build and test wheels
        env:
          # Note: additional cibuildwheel settings are in pyproject.toml.
          CIBW_ARCHS: ${{matrix.conf.arch}}
          CIBW_BUILD: cp3${{matrix.conf.py}}-${{matrix.conf.wh}}_${{matrix.conf.arch}}
        run: |
          python -m pip install cibuildwheel==2.23.3 virtualenv==20.31.2 cmake
          python -m cibuildwheel --output-dir wheelhouse
